//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyJSL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_tarjetas
    {
        public int Número_de_tarjeta { get; set; }
        public string Nombre_Titular { get; set; }
        public System.DateTime Fecha_de_vencimiento { get; set; }
        public int CVV { get; set; }
    }
}
