//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyJSL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forma_de_pago
    {
        public int Numerodepago { get; set; }
        public string Efectivo { get; set; }
        public string Tarjeta { get; set; }
        public int Número_de_tarjeta { get; set; }
    }
}
